### ISSUE TITLE
clarify .travis.yml setting that'll work with packrat AND caching

### ISSUE THREAD

**Issue by maxheld83** [rstudio/packrat#352]
There appears to be some confusion (at least on my part) how to set up travis correctly for packrat so that:

- `packrat/lib*` is cached (because otherwise, build times go crazy for every minor correction)
- the travis cache is properly updated whenever `packrat/packrat.lock` and `packrat/src` change (otherwise, and this is the situation so far, users have to *manually* clear the Travis cache whenever they add/update/remove packages from packrat).

Not a lot of people seem to be using this, though it seems like a fairly important piece to the reproducibility puzzle.

With generous help from @jimhester and @kevinushey on a related [travis issue](https://github.com/travis-ci/travis-ci/issues/7246) I've now figured out what I *think* ought to work in all use cases and offer *both* caching, and cache invalidation.

```
language: r

sudo: false

install:
  - R -e "0" --args --bootstrap-packrat
  - R -e "packrat::restore(restart = FALSE)"

warnings_are_errors: false

cache:
  packages: true
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
    - $TRAVIS_BUILD_DIR/packrat/lib

script:
  - Rscript test-script.R

notifications:
  email: false
```

You can see this `.travis.yml` in action on this reprex [repo](https://github.com/maxheld83/travis-cache-test) and [these builds](https://travis-ci.org/maxheld83/travis-cache-test).

If this makes sense to you people, I'd suggest / do the following:

- [ ] I'll include this via PR into the Travis CI docs
- [ ] I'll add this to the StackExchange question as an answer
- [ ] perhaps you could include this in the `packrat` docs and/or `devtools::use_travis()`/ `devtools::use_packrat()`?

Hope this will be useful to other people.

---

**background on the status quo:**

The settings floating around on [Stack Exchange](http://stackoverflow.com/questions/39009579/using-r-package-source-files-in-packrat-rather-than-cran-with-travis-ci) etc. so far don't accomplish this:

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  directories: $TRAVIS_BUILD_DIR/packrat/
  packages: true
install:
  - R -e "0" --args --bootstrap-packrat
warnings_are_errors: false
```

This caches packrat alright, but Travis won't know when `packrat.lock` and `packrat/src` have actually changed, so it'll fail with something like `package not known` whenever a new one is added etc.
Users have to *manually* delete the travis cache under these settings, which is cumbersome, and easy to forget.
