### ISSUE TITLE
Error in Publishing. "Error in yaml::yaml.load(string, ...) :    Reader error: control characters are not allowed: #98 at 71"

### ISSUE THREAD

**Issue by iMissile** [rstudio/packrat#382]
I have the same situation as written in [https://github.com/rstudio/rsconnect/issues/115](https://github.com/rstudio/rsconnect/issues/115).

Windows 10, RStudio version 1.1.270 (daily build).
Trying to publish to rstudio-connect-1.5.0-7-x86_64 (CentOS 7.x) and got error.

.Rmd document saved in UTF-8.
YAML preamble is:
```
---
title: "Анализ статистики"
author: "Автор"
date: '`r Sys.Date()`'
fontsize: 12pt
output:
  html_document: default
  pdf_document:
    dev: cairo_pdf
    keep_tex: yes
    latex_engine: xelatex
    includes:
        in_header: mystyles.sty
---
```
When I change author: "Автор" to non-cyrillic name, e.g author: "author" everything OK.

packrat version 0.4.8-1

```
> sessionInfo()
R version 3.4.0 Patched (2017-05-08 r72665)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251
[4] LC_NUMERIC=C                    LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11         packrat_0.4.8-1      digest_0.6.12        rprojroot_1.2        bitops_1.0-6        
 [6] backports_1.1.0      magrittr_1.5         evaluate_0.10        BiocInstaller_1.26.0 stringi_1.1.5       
[11] rmarkdown_1.5.9000   RJSONIO_1.3-0        tools_3.4.0          stringr_1.2.0        RCurl_1.95-4.8      
[16] purrr_0.2.2.2        yaml_2.1.14          rsconnect_0.8.3      compiler_3.4.0       base64enc_0.1-3     
[21] PKI_0.1-3            htmltools_0.3.6      knitr_1.16     
```
