### ISSUE TITLE
config.yml dependencies are not discovered

### ISSUE THREAD

**Issue by aronatkins** [rstudio/packrat#510]
Given a Shiny application using the `config` package, `packrat` does not detect dependencies pulled in by the `config.yml` file.

`packrat:::fileDependencies.Rmd` extracts package dependencies from an R Markdown YAML preamble. Should `packrat` do the same for well-known YAML files (thinking about `bookdown.yml`, `site.yml`, and `config.yml`)?

Workaround: Add `library` statements to R code dependencies only used in YAML files.

```r
packrat:::dirDependencies(".")
# => [1] "shiny"  "config"
```

```r
packrat:::fileDependencies("config.yml")
# => Error in packrat:::fileDependencies("config.yml") : 
# =>   Unrecognized file type '/......./config.yml'
```

```r
library(shiny)
library(config)

name <- config::get("name")
launcher <- config::get("launcher")
server <- function(input, output, session) {}
ui <- fluidPage(paste("hello", name, "spawned by", launcher))
shiny::shinyApp(ui = ui, server = server)
```

```yaml
default:
  name: "shiny"
  launcher: "human"
  
rsconnect:
  name: "connected being"
  launcher: !expr ps::ps_name(ps::ps_handle(as.integer(1)))
```
